### PR TITLE
feat: add new flexible size option

### PR DESCRIPTION
**Pull request by ghostdevv**

### CODE REVIEW

**Review by Le0Developer — CHANGES_REQUESTED** [review]
Please add a release entry to HISTORY.md 🙏

**Comment by ghostdevv** [comment]
Should I bump the version? @Le0Developer

**Comment by Le0Developer** [comment]
No, just add to the unreleased section

**Review by Le0Developer — APPROVED** [review]

**Comment by Le0Developer** [comment]
@ghostdevv v1.2.2 has been published on NPM.

**Pull request merged**
